name: peanut
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  shared_preferences: ^2.2.2
  dio: ^5.3.3
  logger: ^2.0.2+1
  flutter_svg: ^2.0.9
  flutter_screenutil: ^5.9.0
  flutter_native_splash: ^2.3.6
  cached_network_image: ^3.3.0
  flutter_spinkit: ^5.2.0
  font_awesome_flutter: ^10.6.0
  curved_navigation_bar: ^1.0.3

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images/ 
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins-Black.ttf
          weight: 900      
        - asset: assets/font/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/font/Poppins-Bold.ttf
          weight: 700
        - asset: assets/font/Poppins-SemiBold.ttf
          weight: 600          
        - asset: assets/font/Poppins-Medium.ttf
          weight: 500
        - asset: assets/font/Poppins-Regular.ttf
          weight: 400
        - asset: assets/font/Poppins-Thin.ttf
          weight: 300          